name: CI

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'invalid' }}
    runs-on: ubuntu-latest

    steps:
    - uses: superbrothers/close-pull-request@v2
      with:
        comment: "You will never get that T-Shirt! 👕🚫"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
